### ISSUE TITLE
Handling $wpdb

### ISSUE THREAD

**Issue by szepeviktor** [berlindb/core#1]
AFAIK if you [return an object](https://github.com/berlindb/core/blob/d6cb580a3ac0b9c3231e8f4ea9965ed0fd9360fc/base.php#L276) (an instance of a class) you get a clone, not the object itself. We had a problem with an OOP ACF plugin that does that as we use Redis caching thus the database is usually not used.

Please see this kind of OOP access of `$wpdb` https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/wordpress/_core-wpdb.php

**Comment by JJJ** [comment]
Not a clone. `$retval` is a byref variable.

It is functionally equivalent to `return $GLOBALS[ $this->db_global ];` but uses a bit more memory for the alias, for the sake of code obviousness.

To test, add...
`$retval->test = wp_rand();`
...after it is assigned.
Now use XDebug to step through related functions.

You should see, the `$wpdb` global contains that `test` value everywhere.
A clone would not have the `test` value.

Feel free to close if that test is sufficient. If I'm wrong, can you code up a way for me to better see what you mean?

**Comment by szepeviktor** [comment]
@JJJ You are right.

```php
<?php

namespace BerlinDB\Database;

// Put base.php beside this file.
require 'base.php';

class Test extends Base {
    public function __construct() {
        $this->db_global = 'wpdb';
        $berlindb = $this->get_db();

        global $wpdb;

        // @see https://www.php.net/manual/en/language.oop5.object-comparison.php
        var_dump($wpdb === $berlindb);

        /*

        $ wp eval-file test.php
        bool(true)

        */
    }
}

new Test();
```
