### ISSUE TITLE
`transition_` Action Not Run on Item Update

### ISSUE THREAD

**Issue by spencerfinnell** [berlindb/core#113]
`transition_item()` uses [`Query::shape_item_id();`](https://github.com/berlindb/core/blob/3e34bcbf7525cc4e5cbd4009803e20d70703d7f5/query.php#L2213) to find the ID of an item being transitioned. If no ID can be derived from the shape then nothing further happens in the transition.

When `Query::update_item()` is used the transition process is never completed because [`Query::update_item()` always unsets the primary column](https://github.com/berlindb/core/blob/3e34bcbf7525cc4e5cbd4009803e20d70703d7f5/query.php#L1909-L1913), ultimately causing `Query::shape_item_id()` to always fail.

**Comment by JJJ** [comment]
Confirmed.

Thinking we just re-add the item ID back on right before. What do you think?

**Comment by spencerfinnell** [comment]
@JJJ Yep, I agree.
