### ISSUE TITLE
Primary Column Can't Be String

### ISSUE THREAD

**Issue by spencerfinnell** [berlindb/core#124]
When setting a primary column if the type of column is not an `int`, `tinyint`, etc, queries will not work. [`get_item_ids()`](https://github.com/berlindb/core/blob/89a1e48788ebae0a32533b0e007a6a1a0cb2f137/src/Database/Query.php#L932) always uses [`wp_parse_id_list`](https://developer.wordpress.org/reference/functions/wp_parse_id_list/) which forces an integer value. This will destroy non-integer results.

Use case: Stripe object IDs are strings and it would be ideal to use those as the primary column when tracking the objects internally.

**Comment by JJJ** [comment]
In your Stripe use case, why not use a traditional numeric auto-incrementing `id` column as the primary, and Stripe object IDs as the next indexed string column?

**Comment by spencerfinnell** [comment]
@JJJ That all seems reasonable. I guess my main thinking was that I will always know the Stripe object ID so I can use it immediately on update and delete calls without first finding the relevant row via the Stripe object ID so I can use the auto incremented primary key.

i.e

```
$coupon = get_coupon_by( 'object_id', $object_id );
$db->delete_item( $coupon->id );
```

vs.

```
$db->delete_item( $object_id );
```

Is there enough caching in play where that doesn't matter? Or are the performance implications of a string based primary key worse?

**Comment by alexstandiford** [comment]
You can also set the stripe ID as a key in your table schema, so you'd get similar speed benefits if it were the primary key.

If you want to be able to delete a record using the Stripe object ID, I would consider extending the delete method to support the stripe ID, or create a a different method specifically for that.

I know it seems wasteful to have to fetch the record from the DB first, but that happens inside Berlin regardless, and it's caching mechanism is smart enough to only query once regardless. It shouldn't have any significant impact on performance, but you still get the benefits mentioned by @JJJ

**Comment by ashleyfae** [comment]
You could just use `wpdb` directly to delete in that instance. Their delete method supports a where clause.

```php
$wpdb->delete( $table_name, array( 'object_id' => $object_id ), array( '%s' ) );
```

Translates into:

```mysql
DELETE FROM my_table WHERE object_id = 'sub_123';
```

**Comment by alexstandiford** [comment]
The issue with what @ashleyfae is suggesting is that it doesn't clear the item's cache. Depending on the situation, it might be better but make sure you take a look at the delete item method to see how it handles updating the cache for the record otherwise you'll end up with unexpected results should you make another query for that record in the same request.

**Comment by spencerfinnell** [comment]
Thanks for the tips/info @ashleyfae and @alexstandiford. As with most things, after rethinking things a bit, I think I can get by with a "normal" primary key without issue. It would be nice to document this expected behavior or throw an error when things are misconfigured, similar to [some of the object properties](https://github.com/berlindb/core/discussions/114). I had to dig down a bit to see where/why things were failing.

**Comment by JJJ** [comment]
> It would be nice to document this expected behavior or throw an error when things are misconfigured

Noted. Great feedback. 👍
