### ISSUE TITLE
PHP 5.6 issue and `clone`

### ISSUE THREAD

**Issue by rmorse** [berlindb/core#129]
Hi again!  I have a PHP Code Sniffer + PHP compat setup (for PHP 5.6) and I'm getting an error that `clone` is a reserved word (in the Table class)

https://github.com/berlindb/core/blob/2d94af59a0d5642b659af7b62c7674811f25df00/src/Database/Table.php#L480-L516

The error:

```
----------------------------------------------------------------------
  | ERROR | Function name, class name, namespace name or constant
     |       | name can not be reserved keyword 'clone' (since
     |       | version 5.0)
----------------------------------------------------------------------
```

Is PHP 5.6 supported (WordPress still does) and should we consider renaming this method?

**Comment by spencerfinnell** [comment]
Related: https://github.com/berlindb/core/issues/38#issuecomment-988864816
