### ISSUE TITLE
Request: add dynamic hook to delete_item method

### ISSUE THREAD

**Issue by robincornett** [berlindb/core#132]
Ref: https://github.com/awesomemotive/easy-digital-downloads/pull/9139#discussion_r851261055

In EDD, we often need to provide a hook for extensions/developers to perform an action when an object is deleted. It would be nice to have a dynamic hook for this in the BerlinDB class instead of having to create hooks manually.

Specifically, what I would like to have at the end of `delete_item`, before the `$result` is returned, is this:

```php
do_action( $this->apply_prefix( "{$this->item_name}_deleted" ), $item_id, $result );
```

Running edd_delete_order would then automatically generate the following hooks straight away:

- edd_order_deleted
- edd_order_item_deleted
- edd_order_address_deleted

The use case we're looking at currently is for deleting an uploaded file when the corresponding order/order meta is deleted.

**Comment by spencerfinnell** [comment]
Related: https://github.com/berlindb/core/issues/56
