### ISSUE TITLE
Date Query extends base from an incorrect namespace.

### ISSUE THREAD

**Issue by alexstandiford** [berlindb/core#15]
I tried to use a date query and Berlin crashed. This was because it was unable to extend the base class. Date is set to extend `Base` in the same namespace as `Date`, however it is in a different namespace.

This is causing issues when trying to run a date query.

**Comment by alexstandiford** [comment]
PR #16

**Comment by JJJ** [comment]
This was committed directly to master, and is considered fixed as a result.

Thanks @alexstandiford 💫
