### ISSUE TITLE
Composer Support Would Be Useful

### ISSUE THREAD

**Issue by alexstandiford** [berlindb/core#5]
Getting ready to try using this in a plugin, and realized that there isn't a composer.json set-up. Since this is generally going to be used as a dependency in a plugin, it would be useful if it had one.

**Comment by Mte90** [comment]
I think that also a bit of example will be not bad, right now I planned to study the code of the plugin mentioned in the readme but is not so easy task

**Comment by szepeviktor** [comment]
Related to #2 

I think majority of plugin developers do not use tools like namespaces and class autoloader. Others (e.g. me) are installing WordPress with composer by default.

**Comment by alexstandiford** [comment]
In the interim, this will work. It doesn't handle autoloading, but once #2 is updated, it could.

```json
{
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "berlindb/core",
        "version": "1.0.0",
        "source": {
          "url": "https://github.com/berlindb/core.git",
          "type": "git",
          "reference": "master"
        }
      }
    }
  ],
  "require": {
    "berlindb/core": "*",
  }
}
```

**Comment by alexstandiford** [comment]
PR: #6

**Comment by Luehrsen** [comment]
You can also add this to add PSR-4 compatibility.


```
	  "autoload": {
	    "psr-4": {
		"BerlinDB\\Database\\": "vendor/berlindb/core/"
	    }
	  },
```

**Comment by szepeviktor** [comment]
What a gigantic hack!
