### ISSUE TITLE
Incorrect use of 'compare' query var instead of 'compare_query'

### ISSUE THREAD

**Issue by ashleyfae** [berlindb/core#8]
Here the key is set to `compare_query` https://github.com/berlindb/core/blob/master/query.php#L445

But later it's referenced as `compare` : https://github.com/berlindb/core/blob/master/query.php#L1281-L1293

I think it used to be `compare` but later got changed and not all instances were updated.

**Comment by szepeviktor** [comment]
One of them seem to be an SQL query chunk, the other a compare clause.

**Comment by JJJ** [comment]
Confirmed. This was only partially changed when the code was originally pushed here from Sugar Calendar, and the Compare query was being cleaned up to better match the Date query.
